AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'schema.rb'

Style/RegexpLiteral:
  EnforcedStyle: percent_r

Layout/LineLength:
  Max: 120

Metrics/ClassLength:
  Max: 300

Metrics/AbcSize:
  Max: 25

Style/MixinUsage:
  Exclude:
    - 'Rakefile'

Style/OptionalBooleanParameter:
  Enabled: false